'use strict'

// tests for authentication
// Generated by serverless-jest-plugin

const mod = require('../aws/authentication')

const jestPlugin = require('serverless-jest-plugin')
const lambdaWrapper = jestPlugin.lambdaWrapper
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' })

describe('authentication', () => {
  beforeAll((done) => {
//  lambdaWrapper.init(liveFunction) // Run the deployed lambda

    done()
  })

  it('implement tests here', () => {
    return wrapped.run({
      body: JSON.stringify({
        username: 'admin',
        password: 'admin'
      })
    }).then((response) => {
      expect(response.statusCode).toEqual(200)
      const body = JSON.parse(response.body)
      expect(body.token).toBeDefined()
    })
  })
})
